### ISSUE TITLE
ข้อมูล vaccine manufacturer วันที่ 27 ซ้ำกับของวันที่ 26

### ISSUE THREAD

**Issue by nathakits** [porames/the-researcher-covid-bot#105]
https://github.com/porames/the-researcher-covid-bot/blob/02927c7f19c64a7712b43315ad800b91fe1036bc/components/gis/data/vaccine-manufacturer-timeseries.json#L1334

**Comment by noppakorn** [comment]
![image](https://user-images.githubusercontent.com/9192053/127272618-269325b8-69fa-400c-b1fd-f590005e29e9.png)
[Slide สถานการณ์การฉีดวัคซีนโควิด 19 จากกรมควบคุมโรค](https://ddc.moph.go.th/vaccine-covid19/diaryPresentMonth/07/10/2021)
ต้นทาง Upload Slide วันที่ 26 และวันที่ 27 ซ้ำกันครับ คงต้องรอทางต้นทางแก้ไขอีกที

**Comment by nathakits** [comment]
@noppakorn ในหน้านี้มีข้อมูลที่ไม่ซ้ำครับ https://ddc.moph.go.th/dcd/pagecontent.php?page=722&dept=dcd

**Comment by porames** [comment]
โอเคครับ
