### ISSUE TITLE
Display unit using months and days instead of year

### ISSUE THREAD

**Issue by plumsirawit** [porames/the-researcher-covid-bot#58]
![image](https://user-images.githubusercontent.com/31605957/122561263-dba47b80-d06b-11eb-9507-3c24cd131475.png)

For a better UX I'd suggest the display to be in months and days instead.

**Comment by porames** [comment]
lol for math dumbs

**Comment by porames** [comment]
resolved, sir. [eb2d852156e7f850fd8043ee9918a51f00c5639d](https://github.com/porames/the-researcher-covid-bot/commit/eb2d852156e7f850fd8043ee9918a51f00c5639d).
will merge soon.
