### ISSUE TITLE
ข้อมูลการฉีดวัคซีนรายจังหวัด ไม่อัพเดท

### ISSUE THREAD

**Issue by Kokoabassplayer** [porames/the-researcher-covid-bot#73]
ข้อมูลอัพเดทล่าสุดถึงวันที่ 7 เกิดปัญหาขึ้นหรือครับ 

ผมใช้แหล่งข้อมูลของคุณในการทำ dashboard ตัวนี้ครับ https://public.tableau.com/app/profile/smith2019/viz/HOWISTHAILANDCOVID-19VACCINATEDCOVERAGE/HOWISTHAILANDCOVID-19VACCINATEDCOVERAGE
ผมติดตามดูทุกวัน เพื่อจะได้ตัดสินใจว่าจะออกจากบ้านได้ไหม ปลอดภัยไหม 
เมื่อเห็นข้อมูลไม่อัพเดทจึงคิดว่าควรมาแจ้งให้ทราบครับ

และขอขอบพระคุณเป็นอย่างสูงที่ได้จัดทำชุดข้อมูลนี้ และหวังเป็นอย่างยิ่งว่าข้อมูลจะมีการอัพเดทต่อๆไปครับ

**Comment by porames** [comment]
ข้อมูลจาก[ต้นทาง](https://datastudio.google.com/u/0/reporting/731713b6-a3c4-4766-ab9d-a6502a4e7dd6/page/vmmOC)ก็ไม่อัพเดทครับ หวังว่าจะกลับมาอัพเดทในเร็ววัน ระหว่างนี้กำลังหาแหล่งข้อมูลใหม่อยู่ครับ เห็นใน[รายงานจากกรมควบคุมโรค](https://ddc.moph.go.th/vaccine-covid19/getFiles/9/1625915101538.pdf)เพิ่มจำนวนวัคซีนที่ฉีดรายจังหวัดแล้ว อาจจะเปลี่ยนมาใช้ข้อมูลจากนี้แทนครับ

**Comment by zuroba** [comment]
@porames  ข้อมูลวัคซีนของ datastudio เห็นโดนจำกัดสิทธิ เข้าไมไ่ด้แล้ว หรือจะตั้ง เป็น private ยาวๆเลย

**Comment by porames** [comment]
@zuroba ตอนนี้เปลี่ยนมาใช้รายงานประจำวันของกรมควบคุมโรคแล้วครับ แปลงตาราง PDF มาเป็นไฟล์ csv โดยคุณ Dylan Jay ครับ
