### ISSUE TITLE
Vaccination by manufacturer data processing

### ISSUE THREAD

**Issue by porames** [porames/the-researcher-covid-bot#85]
ฝากคุณ @noppakorn @plumsirawit หรือผู้สนใจ รีวิว [get-manufacturer.py](https://github.com/porames/the-researcher-covid-bot/blob/master/bot_jobs/vaccination/get-manufacturer.py) ให้หน่อย
แยกฟังก์ชันออกมาเป็นไฟล์ แล้วก็ดู maths ให้หน่อยว่าผม interpolate ข้อมูลวันที่ดึงค่าออกมาจาก PDF ไม่ได้ด้วยข้อมูลวันก่อนหน้า กับคำนวณอัตราการฉีดต่อวันถูกมั้ย

**Comment by plumsirawit** [comment]
The code is not maintainable. Refactor needed. Can't promise but want to help refactoring this.

**Comment by porames** [comment]
@plumsirawit n o t m a i n t a i n a b l e

**Comment by noppakorn** [comment]
Will try to refactor more today with @plumsirawit

**Comment by porames** [comment]
looks cool? @plumsirawit
