### ISSUE TITLE
Track cluster data

### ISSUE THREAD

**Issue by porames** [porames/the-researcher-covid-bot#98]
Tracking factory clusters data from [CCSA briefing PDF](https://media.thaigov.go.th/uploads/public_img/source/249764.pdf). 
The report is published daily at https://www.thaigov.go.th/news/contents/details/29299

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/11443387/126874916-9263ee2d-1603-4dec-b6e8-212cc0c81ccd.png">

**Comment by porames** [comment]
Use data from https://github.com/noppakorn/covid-cluster-thailand
Cr @noppakorn

**Comment by ratthachat** [comment]
Thanks very much for your great web app!
However, on the data-cluster track (แผนที่การระบาด ตำแหน่งการระบาดรายอำเภอ represented by red circles) here
 https://covid-19.researcherth.co/  
It seems Nakhon Ratchasima has never been updated (For examples, see Muang and Pak Chong)

Maybe we can use the data from here krub:
https://covid-19.nakhonratchasima.go.th/frontpage

cc:
@porames @noppakorn

**Comment by noppakorn** [comment]
@ratthachat If you look at our data repo [the-researcher-covid-data](https://github.com/porames/the-researcher-covid-data) we use the data from [data.go.th](https://data.go.th/dataset/covid-19-daily). In the excel file there are published cases data for each province. Many province have their district data clearly published but some province including Nakhon Ratchasima doesn't publish their district data. If we use the data directly from different source the data will not be consistent with data.go.th which we mainly use, so I don't think we can use the province source. But thank you for letting us know about this issue anyway.

**Comment by ratthachat** [comment]
@noppakorn understood krub. In that case, is it a good idea to somehow visualize/remark the provinces which have no update?   So that the user will be cautious about the obsoleted information. 

Thank you again for your great job krub
