### ISSUE TITLE
Separate Github Actions tasks

### ISSUE THREAD

**Issue by porames** [porames/the-researcher-covid-bot#99]
Separate Actions tasks into get cases, vaccination, testing; so one error won't ruin the whole thing.

**Comment by noppakorn** [comment]
# Possible Solution
- Stop using pushing directly to main repo.
- The solution is to push to GitHub wiki for processed data storage.
- This will make the bot jobs totally independent from each other and each job can run in parallel.
- Will make the repo smaller as well (easier to clone for the first time)
